### ISSUE TITLE
"This browser or app may not be secure." issue when trying to sign in.

### ISSUE THREAD

**Issue by shampee** [anirbandey1/chatbot-client#1]
Steps to replicate:
1. `flatpak install flathub io.github.anirbandey1.ChatbotClient`
2. `flatpak run io.github.anirbandey1.ChatbotClient`
3. Sign in

![output](https://github.com/anirbandey1/chatbot-client/assets/328416/9578bd76-017f-4a28-bcee-828fa58962f5)

**Comment by anirbandey1** [comment]
Thank you for pointing this out. The problem has been detected and a solution has been identified. A minor change in the build script should solve this problem.

**Comment by anirbandey1** [comment]
I have fixed the issue and updated the manifest. New flatpakref should be published within a few hours. Could you please verify if the issue has been fixed. Update the app before testing it.

**Comment by shampee** [comment]
Everything seems to be working fine now!
